name: 'Automatic Deployment'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Log in to Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builds image then pushes to Docker Hub
      - name: Build Docker Image
        # kubectl apply -f issuer-config.yml
        run: |
          sed -i'' -e 's/USER/${{secrets.DB_USER}}/g' -e 's/PASSWORD/${{secrets.DB_PASS}}/g'  -e 's/DSN/${{secrets.DSN}}/g' src/dao.php
          docker build --tag  ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}:${{GITHUB.SHA}} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}:${{GITHUB.SHA}}
  deploy-to-k3s:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set Kubernetes context
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          # Contents of kubeconfig file
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # Deploys to K3s
      - name: Deploy to K3s
        run: |
          kubectl create ns ${{ secrets.APP_NAME }}-system || echo "Skipping..."
          
          sed -i'' -e 's/DOCKERHUB_USERNAME/${{ secrets.DOCKERHUB_USERNAME }}/g' -e 's/APP_NAME/${{ secrets.APP_NAME }}/g' -e 's/GIT_HASH/${{GITHUB.SHA}}/g' ./kubernetes/deployment.yml
          kubectl apply -f ./kubernetes/deployment.yml
          
          sed -i'' -e 's/APP_NAME/${{ secrets.APP_NAME }}/g' ./kubernetes/service.yml
          kubectl apply -f ./kubernetes/service.yml
          
          sed -i'' -e 's/APP_NAME/${{ secrets.APP_NAME }}/g' -e 's/DOMAIN/${{ secrets.DOMAIN }}/g' ./kubernetes/ingress.yml
          kubectl apply -f ./kubernetes/ingress.yml
